services:
  company-service:
    build: ./company-service
    ports:
      - "5001:5001"
    env_file:
      - .env

  document-service:
    build: ./document-service
    ports:
      - "5002:5002"
    env_file:
      - .env
      
  s3-service:
    build: ./s3-service
    ports:
      - "5003:5003"
    env_file:
      - .env

  ai-service:
    build:
      context: .
      dockerfile: ./ai-service/Dockerfile
    ports:
      - "5004:5004"
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}

  llm-service:
    build:
      context: .
      dockerfile: ./llm-service/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - tag-service
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID2}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY2}
      - AWS_REGION=${AWS_REGION2}
      - CLAUDE_MODEL_ID=${CLAUDE_MODEL_ID}
      - TAG_SERVICE_URL=http://tag-service:5007

  prediction-service:
    build: ./prediction-service
    ports:
      - "5006:5006"
    depends_on:
      - ai-service
      - llm-service
      - text-extraction-service
    env_file:
      - .env
    environment:
      - AI_SERVICE_TIMEONE=120
      - LLM_SERVICE_TIMEOUT=120

  tag-service:
    build: ./tag-service
    ports:
      - "5007:5007"
    env_file:
      - .env
    environment:
      # These must exist in your .env file
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5007/tags"]
      interval: 15s
      timeout: 5s
      retries: 5

  text-extraction-service:
    build: ./text-extraction-service
    ports:
      - "5008:5008"
    env_file:
      - .env
    environment:
      - PORT=5008

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - company-service
      - document-service
      - s3-service
      - ai-service
      - llm-service
      - prediction-service
      - text-extraction-service
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - company-service
      - s3-service
      - document-service
      - ai-service
      - llm-service
      - prediction-service
      - tag-service
      - text-extraction-service
