services:
  company-service:
    build: ./company-service
    ports:
      - "5001:5001"
    env_file:
      - .env

  document-service:
    build: ./document-service
    ports:
      - "5002:5002"
    env_file:
      - .env
      
  s3-service:
    build: ./s3-service
    ports:
      - "5003:5003"
    env_file:
      - .env

  ai-service:
    build: ./ai-service
    ports: 
      - "5004:5004"
    env_file:
      - .env

  llm-service:
    build: ./llm-service
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID2}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY2}
      - AWS_REGION=${AWS_REGION2}
      - CLAUDE_MODEL_ID=${CLAUDE_MODEL_ID}

  prediction-service:
    build: ./prediction-service
    ports:
      - "5006:5006"
    depends_on:
      - ai-service
      - llm-service
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - company-service
      - s3-service
      - document-service
      - ai-service
      - llm-service
      - prediction-service
