version: '3.8'
services:
  company-service:
    build: ./company-service
    ports:
      - "5001:5001"
    env_file:
      - .env
      
  s3-service:
    build: ./s3-service
    ports:
      - "5003:5003"
    env_file:
      - .env

  ai-service:
    build:
      context: ./ai-service
    environment:
      HIER_BUNDLE_PATH: /models/hier_bundle.joblib
      HIER_PATH: /app/shared/tag_hierarchy.json
      ENABLE_OCR: "1"
      MAX_UPLOAD_MB: "50"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ../models:/models:ro
      - ./ai-service/shared:/app/shared:ro
    # 🔽 run Flask with WSGI worker, binding to 5004
    command: >
      gunicorn app:app
      --bind 0.0.0.0:5004
      --workers 2
      --timeout 120
    healthcheck:
      # 🔽 point healthcheck to 5004 now
      test: ["CMD", "curl", "-fsS", "http://localhost:5004/ai/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped



  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - company-service
    - s3-service
    - ai-service