version: '3.8'
services:
  company-service:
    build: ./company-service
    ports:
      - "5001:5001"
    env_file:
      - .env

  categories-service:
    build: ./categories-service
    ports:
      - "5002:5002"
    env_file:
      - .env

  ai-service:
    build:
      context: ./ai-service
    environment:
      HIER_BUNDLE_PATH: /models/hier_bundle.joblib
      HIER_PATH: /app/shared/tag_hierarchy.json
      ENABLE_OCR: "1"
      MAX_UPLOAD_MB: "50"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ../models:/models:ro                # model artifact lives at repo-root/models
      - ./ai-service/shared:/app/shared:ro  # hierarchy json if present
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/ai/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend-demo:/usr/share/nginx/html:ro
    depends_on:
      company-service:
        condition: service_started        # no healthcheck needed
      categories-service:
        condition: service_started        # no healthcheck needed
      ai-service:
        condition: service_healthy        # needs a healthcheck
  restart: unless-stopped